[project]
name = "bothackathon"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "promptic>=5.5.1",
    "pytelegrambotapi>=4.26.0",
    "requests>=2.32.4",
    "state>=0.1.1.dev0",
]

[dependency-groups]
dev = [
    "ipython>=9.0.0",
]
